codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

flags:
  unit-tests:
    carryforward: true
  integration-tests:
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
